general.import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml",
]
# good themes:
# coolnight, tokyonight, catppuccin, kanagawa, deep_space, nord/nordic, rose-pine, embark, catpuccin
# github-dark

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

# decorations = "transparent"
decorations = "buttonless"
# decorations = "none"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
size = 17

[font.normal]
# family = "MesloLGS Nerd Font Mono"
# family = "JetBrainsMono Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Hack Nerd Font"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"
