import = [
  "~/.config/alacritty/themes/themes/embark.toml"
]
# good themes: coolnight, tokyonight, catppuccin, kanagawa, deep_space, nord/nordic, rose-pine, embark

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

# decorations = "transparent"
decorations = "buttonless"

opacity = 0.9
blur = false

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
