import = [
  "~/.config/alacritty/themes/themes/embark.toml"
]
# good themes: coolnight, tokyonight, catppuccin, kanagawa, deep_space, nord/nordic, rose-pine, embark

[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

# decorations = "transparent"
decorations = "buttonless"

opacity = 0.95
blur = false

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
size = 17

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[ font.bold ]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[ font.italic ]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[ font.bold_italic ]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

